trigger:
  branches:
    include:
      - main
      - feature/*

steps:
  - checkout: self
    fetchDepth: 0

  - task: SonarQubePrepare@7
    inputs:
      SonarQube: 'sq2025-connection'
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'jhps-github-frontend'
      cliProjectName: 'jhps-github-frontend'
      cliSources: './vulnerable-frontend'
      extraProperties: |
        sonar.qualitygate.wait
  # - task: SonarCloudPrepare@3
  #   inputs:
  #     SonarQube: 'sqcloud'
  #     organization: 'jeremyho'
  #     scannerMode: 'cli'
  #     configMode: 'manual'
  #     cliProjectKey: 'jhps-test-frontend'
  #     cliProjectName: 'jhps-test-frontend'
  #     cliSources: './vulnerable-frontend'

  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd vulnerable-frontend
        npm run build
        npm install
    displayName: 'Build frontend'

  # Run Code Analysis task
  - task: SonarQubeAnalyze@7
    continueOnError: false
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
  # - task: SonarCloudAnalyze@3
  #   inputs:
  #     jdkversion: 'JAVA_HOME_17_X64'

  # Publish Quality Gate Result task
  # - task: SonarQubePublish@7
  #   inputs:
  #     pollingTimeoutSec: '300'
  # - task: SonarCloudPublish@3
  #   inputs:
  #     pollingTimeoutSec: '300'

  - task: SonarQubePrepare@7
    inputs:
      SonarQube: 'sq2025-connection'
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'jhps-github-backend'
      cliProjectName: 'jhps-github-backend'
      cliSources: './vulnerable-backend'
      extraProperties: |
        sonar.qualitygate.wait
  # - task: SonarCloudPrepare@3
  #   inputs:
  #     SonarQube: 'sqcloud'
  #     organization: 'jeremyho'
  #     scannerMode: 'cli'
  #     configMode: 'manual'
  #     cliProjectKey: 'jhps-test-backend'
  #     cliProjectName: 'jhps-test-backend'
  #     cliSources: './vulnerable-backend'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd vulnerable-backend
        npm run build
        npm install
    displayName: 'Build backend'

  # Run Code Analysis task
  - task: SonarQubeAnalyze@7
    continueOnError: false
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
  # - task: SonarCloudAnalyze@3
  #   inputs:
  #     jdkversion: 'JAVA_HOME_17_X64'  

  # Publish Quality Gate Result task
  # - task: SonarQubePublish@7
  #   inputs:
  #     pollingTimeoutSec: '300'
  # - task: SonarCloudPublish@3
  #   inputs:
  #     pollingTimeoutSec: '300'
