pr:
  branches:
    include:
    - main
    
steps:
  - checkout: self
    fetchDepth: 0

  - task: SonarQubePrepare@7
    inputs:
      SonarQube: 'sq2025-connection'
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'jhps-github-frontend'
      cliProjectName: 'jhps-github-frontend'
      cliSources: './vulnerable-frontend'
      # extraProperties: |
      #   sonar.qualitygate.wait=true
`
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd vulnerable-frontend
        npm run build
        npm install
    displayName: 'Build frontend'

  # Run Code Analysis task
  - task: SonarQubeAnalyze@7
    # continueOnError: false
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'

  - task: SonarQubePrepare@7
    inputs:
      SonarQube: 'sq2025-connection'
      scannerMode: 'cli'
      configMode: 'manual'
      cliProjectKey: 'jhps-github-backend'
      cliProjectName: 'jhps-github-backend'
      cliSources: './vulnerable-backend'
      # extraProperties: |
      #   sonar.qualitygate.wait=true
        
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '14.x'
    displayName: 'Install Node.js'

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        cd vulnerable-backend
        npm run build
        npm install
    displayName: 'Build backend'

  # Run Code Analysis task
  - task: SonarQubeAnalyze@7
    # continueOnError: false
    inputs:
      jdkversion: 'JAVA_HOME_17_X64'
